# Generated by Django 6.0.5 on 2026-05-18 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa produktu')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='Kod SKU')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis produktu')),
                ('current_stock', models.IntegerField(default=0, verbose_name='Aktualny stan magazynowy')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Dostawa'), ('OUT', 'Wydanie')], max_length=3, verbose_name='Typ operacji')),
                ('quantity', models.PositiveIntegerField(verbose_name='Ilość sztuk')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data i godzina operacji')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product', verbose_name='Produkt')),
            ],
        ),
    ]
