# Generated by Django 6.0.5 on 2026-06-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Telefon', 'Telefon'), ('Laptop', 'Laptop'), ('Monitor', 'Monitor'), ('Akcesoria', 'Akcesoria'), ('Drukarka', 'Drukarka'), ('Inne', 'Inne')], default='Inne', max_length=50),
        ),
    ]
