# Generated by Django 6.0.5 on 2026-06-07 18:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name='Data i godzina operacji'),
        ),
    ]
